import Image_1 from "../../assets/img/productImg/p_1.jpg";
import Image_2 from "../../assets/img/productImg/p_2.jpg";
import Image_4 from "../../assets/img/productImg/p_4.jpg";
import Image_5 from "../../assets/img/productImg/p_5.jpg";
import Image_6 from "../../assets/img/productImg/p_6.jpg";
import Image_7 from "../../assets/img/productImg/p_7.jpg";
import Image_8 from "../../assets/img/productImg/p_3.jpg";
import Image_9 from "../../assets/img/productImg/p_9.jpg";
import Image_10 from "../../assets/img/productImg/p_10.jpg";

export const allProducts = [
  {
    id: 1,
    price: "199.99",
    itemTotalPrice: "199.99",
    quantity: 1,
    wishListItem: 0,
    title: "Somersung Sonic X500 Basic",
    image: Image_1,
    Rating: 3.5,
  },
  {
    id: 2,
    price: "60.34",
    itemTotalPrice: "60.34",
    quantity: 1,
    wishListItem: 0,
    title: "Digital Thermometer X30-Pro",
    image: Image_2,
    Rating: 3,
  },
  {
    id: 3,
    price: "369.87",
    itemTotalPrice: "369.87",
    quantity: 1,
    wishListItem: 0,
    title: "Oxygen concentrator m KTS-5000",
    image: Image_4,
    Rating: 5,
  },
  {
    id: 4,
    price: "77.65",
    itemTotalPrice: "77.65",
    quantity: 1,
    wishListItem: 0,
    title: "Blood Pressure Monitor",
    image: Image_5,
    Rating: 3.5,
  },
  {
    id: 5,
    price: "60.99",
    itemTotalPrice: "60.99",
    quantity: 1,
    wishListItem: 0,
    title: "Automatic blood pressure monitor",
    image: Image_6,
    Rating: 3.5,
  },
  {
    id: 6,
    price: "70.99",
    itemTotalPrice: "70.99",
    quantity: 1,
    wishListItem: 0,
    title: " Blood Sugar Test Machine",
    image: Image_7,
    Rating: 4,
  },
  {
    id: 8,
    price: "299.99",
    itemTotalPrice: "299.99",
    quantity: 1,
    wishListItem: 0,
    title: "Somersung Sonic X2000 Pro Black",
    image: Image_8,
    Rating: 4.5,
  },
  {
    id: 9,
    price: "53.75",
    itemTotalPrice: "53.75",
    quantity: 1,
    wishListItem: 0,
    title: "Extractor used to  teeth",
    image: Image_9,
    Rating: 3.5,
  },
  {
    id: 10,
    price: "577.75",
    itemTotalPrice: "577.75",
    quantity: 1,
    wishListItem: 1,
    title: "Extractor used to  teeth",
    image: Image_5,
    Rating: 3.5,
  },
  {
    id: 11,
    price: "452.75",
    itemTotalPrice: "452.75",
    quantity: 1,
    wishListItem: 0,
    title: "Extractor used to  teeth",
    image: Image_9,
    Rating: 3.5,
  },
  {
    id: 12,
    price: "53.75",
    itemTotalPrice: "53.75",
    quantity: 1,
    wishListItem: 0,
    title: "Extractor used to  teeth",
    image: Image_4,
    Rating: 3.5,
  },
  {
    id: 13,
    price: "350.75",
    itemTotalPrice: "350.75",
    quantity: 1,
    wishListItem: 0,
    title: "Blue Hot Water Bottle, 2 Quart Capacity",
    image: Image_10,
    Rating: 4.5,
  },
];
